name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: app' tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: automated tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci #cf. https://docs.npmjs.com/cli/v9/commands/npm-ci
      - run: npm run test
